# -*- coding: utf-8 -*-
"""Set of tweets.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_4axJx1jbEpbwNQbXBJImdsVzsySn489
"""

import tweepy
import json
import csv
import re
from pymongo import mongo_client

def search_hashtags(consumer_key, consumer_secret, access_token, access_token_secret, hashtag_phrase):

    # authentication for accesing twitter
    auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(access_token, access_token_secret)

    api = tweepy.API(auth, wait_on_rate_limit=True)  #intiliaze the Tweepy API

    fname = '_'.join(re.findall(r"#(\w+)",hashtag_phrase)) # naming of file

    with open('%s.csv' % (fname), 'w') as file:

        w = csv.writer(file)

        #write header row to spreadsheet
        w.writerow(['timestamp', 'tweet_text', 'username', 'all_hashtags', 'followers_count'])

        #for each tweet matching our hashtags, write relevant info to the spreadsheet
        for tweet in tweepy.Cursor(api.search, q=hashtag_phrase+' -filter:retweets', lang="it", tweet_mode='extended').items(100):
            w.writerow([tweet.created_at, tweet.full_text.replace('\n',' ').encode('utf-8'), tweet.user.screen_name.encode('utf-8'), [e['text'] for e in tweet._json['entities']['hashtags']], tweet.user.followers_count])

consumer_key = input("Pl7wJC0frX8zOFeZjDf4glsJP")
consumer_secret = input("FmSACNFbcWxFfZT3BzE3D10s81s87PgScyVX6RM2TySnGxOnNA")
access_token = input("1330887433634902017-xC5kqdWMRpMLDVWt7LneSck2vXvgQF")
access_token_secret = input("zZPNRfvX1pNkoUvj5MaG5Y1MzqVn2QB5gOPpmNPRDjwdC")

hashtag_phrase = input('Hashtag Phrase ')

if __name__ == '__main__':
    search_hashtags(consumer_key, consumer_secret, access_token, access_token_secret, hashtag_phrase)







